import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/layouts/layout";
import { PageHeader } from "../components/molecules/pageHeader";
import { Awards } from "../components/organisms/awardsSection/awardsSection-container";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>The Movie Awards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeader title="Awards 2022" />
        <Awards />
      </Layout>
    </>
  );
};

export default Home;
